store:
  memory:
    limit: 100000
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false
packages:
  'eslint-config-motley-typescript':
    access: $anonymous
    publish: $anonymous
  '**':
    access: $anonymous
    publish: $anonymous
    proxy: npmjs
middlewares:
  audit:
    enabled: true