store:
  memory:
    limit: 100000
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false
    max_fails: 100
packages:
  'eslint-config-motley-typescript':
    access: $all
    publish: $all
  '**':
    access: $all
    publish: $all
    proxy: npmjs
log: { type: stdout, format: pretty, level: http }

