name: Publish eslint-config-motley and eslint-config-motley-typescript

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run test:ci
  publish-eslint-config-motley:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: './packages/eslint-config-motley/package.json'
  publish-eslint-config-typescript:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: './packages/eslint-config-motley-typescript/package.json'